// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: walsync.proto

package walsyncpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalSync_ShipWal_FullMethodName      = "/walsync.WalSync/ShipWal"
	WalSync_ShipSnapshot_FullMethodName = "/walsync.WalSync/ShipSnapshot"
	WalSync_Health_FullMethodName       = "/walsync.WalSync/Health"
)

// WalSyncClient is the client API for WalSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalSyncClient interface {
	// Ship WAL chunk (incremental)
	ShipWal(ctx context.Context, in *WalChunk, opts ...grpc.CallOption) (*Ack, error)
	// Ship full DB snapshot
	ShipSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*Ack, error)
	// Health check
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type walSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewWalSyncClient(cc grpc.ClientConnInterface) WalSyncClient {
	return &walSyncClient{cc}
}

func (c *walSyncClient) ShipWal(ctx context.Context, in *WalChunk, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, WalSync_ShipWal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walSyncClient) ShipSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, WalSync_ShipSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walSyncClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, WalSync_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalSyncServer is the server API for WalSync service.
// All implementations must embed UnimplementedWalSyncServer
// for forward compatibility.
type WalSyncServer interface {
	// Ship WAL chunk (incremental)
	ShipWal(context.Context, *WalChunk) (*Ack, error)
	// Ship full DB snapshot
	ShipSnapshot(context.Context, *Snapshot) (*Ack, error)
	// Health check
	Health(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedWalSyncServer()
}

// UnimplementedWalSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalSyncServer struct{}

func (UnimplementedWalSyncServer) ShipWal(context.Context, *WalChunk) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ShipWal not implemented")
}
func (UnimplementedWalSyncServer) ShipSnapshot(context.Context, *Snapshot) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ShipSnapshot not implemented")
}
func (UnimplementedWalSyncServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedWalSyncServer) mustEmbedUnimplementedWalSyncServer() {}
func (UnimplementedWalSyncServer) testEmbeddedByValue()                 {}

// UnsafeWalSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalSyncServer will
// result in compilation errors.
type UnsafeWalSyncServer interface {
	mustEmbedUnimplementedWalSyncServer()
}

func RegisterWalSyncServer(s grpc.ServiceRegistrar, srv WalSyncServer) {
	// If the following call panics, it indicates UnimplementedWalSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalSync_ServiceDesc, srv)
}

func _WalSync_ShipWal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalChunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalSyncServer).ShipWal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalSync_ShipWal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalSyncServer).ShipWal(ctx, req.(*WalChunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalSync_ShipSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Snapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalSyncServer).ShipSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalSync_ShipSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalSyncServer).ShipSnapshot(ctx, req.(*Snapshot))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalSync_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalSyncServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalSync_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalSyncServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// WalSync_ServiceDesc is the grpc.ServiceDesc for WalSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "walsync.WalSync",
	HandlerType: (*WalSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShipWal",
			Handler:    _WalSync_ShipWal_Handler,
		},
		{
			MethodName: "ShipSnapshot",
			Handler:    _WalSync_ShipSnapshot_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _WalSync_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "walsync.proto",
}
