// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: walsync.proto

package walsyncpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalChunk) Reset() {
	*x = WalChunk{}
	mi := &file_walsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalChunk) ProtoMessage() {}

func (x *WalChunk) ProtoReflect() protoreflect.Message {
	mi := &file_walsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalChunk.ProtoReflect.Descriptor instead.
func (*WalChunk) Descriptor() ([]byte, []int) {
	return file_walsync_proto_rawDescGZIP(), []int{0}
}

func (x *WalChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WalChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbData        []byte                 `protobuf:"bytes,1,opt,name=db_data,json=dbData,proto3" json:"db_data,omitempty"`
	WalData       []byte                 `protobuf:"bytes,2,opt,name=wal_data,json=walData,proto3" json:"wal_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_walsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_walsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_walsync_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetDbData() []byte {
	if x != nil {
		return x.DbData
	}
	return nil
}

func (x *Snapshot) GetWalData() []byte {
	if x != nil {
		return x.WalData
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	AppliedOffset int64                  `protobuf:"varint,3,opt,name=applied_offset,json=appliedOffset,proto3" json:"applied_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_walsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_walsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_walsync_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Ack) GetAppliedOffset() int64 {
	if x != nil {
		return x.AppliedOffset
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_walsync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_walsync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_walsync_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	DbSize        int64                  `protobuf:"varint,2,opt,name=db_size,json=dbSize,proto3" json:"db_size,omitempty"`
	WalSize       int64                  `protobuf:"varint,3,opt,name=wal_size,json=walSize,proto3" json:"wal_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_walsync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_walsync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_walsync_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetDbSize() int64 {
	if x != nil {
		return x.DbSize
	}
	return 0
}

func (x *HealthResponse) GetWalSize() int64 {
	if x != nil {
		return x.WalSize
	}
	return 0
}

var File_walsync_proto protoreflect.FileDescriptor

const file_walsync_proto_rawDesc = "" +
	"\n" +
	"\rwalsync.proto\x12\awalsync\"6\n" +
	"\bWalChunk\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\">\n" +
	"\bSnapshot\x12\x17\n" +
	"\adb_data\x18\x01 \x01(\fR\x06dbData\x12\x19\n" +
	"\bwal_data\x18\x02 \x01(\fR\awalData\"R\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x0eapplied_offset\x18\x03 \x01(\x03R\rappliedOffset\"\a\n" +
	"\x05Empty\"T\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x17\n" +
	"\adb_size\x18\x02 \x01(\x03R\x06dbSize\x12\x19\n" +
	"\bwal_size\x18\x03 \x01(\x03R\awalSize2\x99\x01\n" +
	"\aWalSync\x12*\n" +
	"\aShipWal\x12\x11.walsync.WalChunk\x1a\f.walsync.Ack\x12/\n" +
	"\fShipSnapshot\x12\x11.walsync.Snapshot\x1a\f.walsync.Ack\x121\n" +
	"\x06Health\x12\x0e.walsync.Empty\x1a\x17.walsync.HealthResponseB4Z2github.com/maulanashalihin/walsync/proto/walsyncpbb\x06proto3"

var (
	file_walsync_proto_rawDescOnce sync.Once
	file_walsync_proto_rawDescData []byte
)

func file_walsync_proto_rawDescGZIP() []byte {
	file_walsync_proto_rawDescOnce.Do(func() {
		file_walsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_walsync_proto_rawDesc), len(file_walsync_proto_rawDesc)))
	})
	return file_walsync_proto_rawDescData
}

var file_walsync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_walsync_proto_goTypes = []any{
	(*WalChunk)(nil),       // 0: walsync.WalChunk
	(*Snapshot)(nil),       // 1: walsync.Snapshot
	(*Ack)(nil),            // 2: walsync.Ack
	(*Empty)(nil),          // 3: walsync.Empty
	(*HealthResponse)(nil), // 4: walsync.HealthResponse
}
var file_walsync_proto_depIdxs = []int32{
	0, // 0: walsync.WalSync.ShipWal:input_type -> walsync.WalChunk
	1, // 1: walsync.WalSync.ShipSnapshot:input_type -> walsync.Snapshot
	3, // 2: walsync.WalSync.Health:input_type -> walsync.Empty
	2, // 3: walsync.WalSync.ShipWal:output_type -> walsync.Ack
	2, // 4: walsync.WalSync.ShipSnapshot:output_type -> walsync.Ack
	4, // 5: walsync.WalSync.Health:output_type -> walsync.HealthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_walsync_proto_init() }
func file_walsync_proto_init() {
	if File_walsync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_walsync_proto_rawDesc), len(file_walsync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_walsync_proto_goTypes,
		DependencyIndexes: file_walsync_proto_depIdxs,
		MessageInfos:      file_walsync_proto_msgTypes,
	}.Build()
	File_walsync_proto = out.File
	file_walsync_proto_goTypes = nil
	file_walsync_proto_depIdxs = nil
}
